name: CI/CD

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  CodeStyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install flake8
      - name: Codestyle
        run: python -m flake8 ./ --ignore=F401,E402
  
  Tests:
    runs-on: ubuntu-latest
    needs: CodeStyle
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: |
          pip install -e '.[test]'
          python -m coverage run -m pytest
          python -m coverage report

  DeplloyToDockerHub:
    runs-on: ubuntu-latest
    needs: Tests
    steps:
        - name: Getting sources
          uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build
          run: |
            docker build -t ksuvot/final-lab .
        - name: Push
          run: |
            docker push ksuvot/final-lab
#         - name: Upload
#           uses: ishworkh/docker-image-artifact-upload@v1
#           with:
#             image: "ksuvot/final-lab:latest"
                   
  RunOnHeroku:
    runs-on: ubuntu-latest
    needs: DeplloyToDockerHub
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ksuvot-final-lab"
          heroku_email: ${{secrets.HEROKU_EMAIL}}

  RunOnAzure:
    runs-on: ubuntu-latest
    needs: DeplloyToDockerHub
    steps:
    - name: run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.AZURE_NAME }}
        password: ${{ secrets.AZURE_PAS }}
        port: 22
        script: |
          docker run -p 8080:5000 ksuvot/final-lab
          curl -Is http://172.17.0.2:5000/ | head -1
        # HTTP/1.0 200 OK

  RunOnAzure2:
    runs-on: ubuntu-latest
    needs: DeplloyToDockerHub
    steps:
    - name: run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.AZURE_NAME }}
        password: ${{ secrets.AZURE_PAS }}
        port: 22
        script: |
          curl -Is http://172.17.0.2:50007/ | head -1

  TelegramNotifications_error:
    runs-on: ubuntu-latest
    needs: RunOnHeroku
    steps:
      - name: Notification -> error
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ❌ error
      - name: Notification -> error
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ✅ error

#   TelegramNotifications_done:
#     runs-on: ubuntu-latest
#     needs: RunOnHeroku
#     steps:
#       - name: Notification
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: ✅ done
